# SPDX-License-Identifier: MIT
# Vegan Activists (VeganActivists@proton.me)

trailingComma: all
singleQuote: true

overrides:
  - files: "*.md"
    options:
      printWidth: 120
      proseWrap: always
      semi: true
      singleQuote: true
      quoteProps: as-needed
      trailingComma: all
